### ISSUE TITLE
classement des arrêts

### ISSUE THREAD

**Issue by ghost** [haum/timeoMAP#1]
est il possible de classer les arrêts par ordre de passage du bus?

cela peut être fait grâce aux "values" des listes déroulantes des arrêts

```
<option value='268569345_765'>BEAUREGARD (765)</option>
<option value='268569346_763'>MOREAU (763)</option>
<option value='268569347_599'>RACINE (599)</option>
...
```

dans cet exemple 345, 346, 347, etc...

**Comment by matael** [comment]
Malheureusement les listes ne sont pas toutes classées à ce que j'ai pu voir....
